
version: 2

sources:
  - name: instacart_db
    description: "Instacart db clone"
    database: instacart_restore
    schema: public
    tables:
      - name: customers
        description: "The raw Instacart customer data"
        columns:
          - name: customer_id
            description: "PK column for the customers table"
            tests:
              - unique
              - not_null
          - name: gender
            description: "Customer gender data"
            tests:
              - accepted_values:
                  values:
                    - Male
                    - Female
      - name: products
        description: "The raw Instacart products data"
        columns: 
          - name: product_id
            description: "PK column for products table"
            tests:
              - unique
              - not_null
          - name: aisle_id
            description: "FK column relating to the aisles table"
            tests:
              - not_null
              - relationships:
                  to: ref('instacart_db', 'aisles')
                  field: aisle_id
          - name: department_id
            description: "FK column relating to the departments table"
            tests:
              - not_null
              - relationships:
                  to: ref('instacart_db', 'departments')
                  field: department_id
      - name: orders
        description: "The raw Instacart orders data"
        columns:
          - name: order_id
            description: "PK column for the orders table"
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "FK column relating to the customers table"
            tests:
              - not_null
              - relationships:
                  to: ref('instacart_db', 'customers')
                  field: customer_id
          - name: product_id
            description: "FK column relating to the products table"
            tests:
              - not_null
              - relationships: 
                  to: ref('instacart_db', 'products')
                  field: product_id
          - name: order_status
            description: "Order status of all orders"
            tests:
              - accepted_values:
                  values:
                    - Delivered
                    - Processing
                    - Shipped
      - name: aisles
        description: "The raw Instacart aisles data"
        columns: 
          - name: aisle_id
            description: "PK column for aisles table"
            tests:
              - not_null
              - unique
      - name: department
        description: "The raw Instacart departments data"
        columns: 
          - name: department_id
            description: "PK column for dept table"
            tests:
              - not_null
              - unique
      - name: payment
        description: "The raw Instacart payments data"
        columns: 
          - name: payment_id
            description: "PK column for payments table"  